Repository KB-ITYL-Banklab/Banklab-backend, pull requests merged in 2025-08, with the labels that each got.

#23 [BNK-152] 로그인 고도화
  src/main/java/com/banklab/common/redis/RedisKeyUtil.java
  src/main/java/com/banklab/common/util/PasswordValidator.java
  src/main/java/com/banklab/exception/CommonExceptionAdvice.java
  src/main/java/com/banklab/member/controller/MemberController.java
  src/main/java/com/banklab/member/mapper/MemberMapper.java
  src/main/java/com/banklab/member/service/MemberService.java
  src/main/java/com/banklab/member/service/MemberServiceImpl.java
  src/main/java/com/banklab/oauth/service/KakaoAuthService.java
  src/main/java/com/banklab/security/account/dto/AuthResultDTO.java
  src/main/java/com/banklab/security/config/SecurityConfig.java
  src/main/java/com/banklab/security/controller/AuthController.java
  src/main/java/com/banklab/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/banklab/security/handler/LoginSuccessHandler.java
  src/main/java/com/banklab/security/service/LoginUserProvider.java
  src/main/java/com/banklab/security/util/JwtProcessor.java
  src/main/resources/com/banklab/member/mapper/MemberMapper.xml
  src/test/java/com/banklab/security/util/JwtProcessorTest.java
Labels: ✨ feature

#24 [BNK-159] Refactor : 계좌 연결 인가부분 리팩토링
  src/main/java/com/banklab/account/controller/AccountController.java
  src/main/java/com/banklab/codef/service/RequestConnectedId.java
  src/main/resources/application.properties
Labels: 🔁 refactor

#25 [BNK-159] Refactor : 거래내역 컨트롤러 사용자 인증 수정
  src/main/java/com/banklab/transaction/controller/TransactionApiController.java
Labels: 🔁 refactor

#30 [BNK-89] Feat : 증권 연동 기능 구현
  src/main/java/com/banklab/account/controller/AccountController.java
  src/main/java/com/banklab/codef/service/RequestConnectedId.java
  src/main/java/com/banklab/codef/util/CommonConstant.java
  src/main/java/com/banklab/config/RootConfig.java
  src/main/java/com/banklab/config/ServletConfig.java
  src/main/java/com/banklab/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/banklab/stock/controller/StockApiController.java
  src/main/java/com/banklab/stock/domain/StockVO.java
  src/main/java/com/banklab/stock/dto/StockDTO.java
  src/main/java/com/banklab/stock/dto/StockRequestDTO.java
  src/main/java/com/banklab/stock/mapper/StockMapper.java
  src/main/java/com/banklab/stock/service/StockResponse.java
  src/main/java/com/banklab/stock/service/StockService.java
  src/main/java/com/banklab/stock/service/StockServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/com/banklab/stock/mapper/StockMapper.xml
  src/test/java/com/banklab/category/service/CategoryServiceTest.java
  src/test/java/com/banklab/codef/util/RequestConnectedIdTest.java
  src/test/java/com/banklab/stock/service/StockResponseTest.java
  src/test/java/com/banklab/transaction/service/AsyncTransactionServiceImplTest.java
  src/test/java/com/banklab/transaction/service/TransactionServiceImplTest.java
  src/test/resources/application.properties
Labels: 🔁 refactor, ✨ feature

#35 [BNK-168} 경제컨텐츠 버그 수정
  src/main/java/com/banklab/common/response/ApiResponse.java
  src/main/java/com/banklab/config/RootConfig.java
  src/main/java/com/banklab/financeContents/controller/FinanceQuizController.java
  src/main/java/com/banklab/financeContents/controller/FinanceTermsController.java
  src/main/java/com/banklab/financeContents/controller/StockController.java
  src/main/java/com/banklab/financeContents/controller/UpbitController.java
  src/main/java/com/banklab/financeContents/domain/FinanceStockVO.java
  src/main/java/com/banklab/financeContents/domain/FinanceTermVO.java
  src/main/java/com/banklab/financeContents/domain/FinanceUpbit.java
  src/main/java/com/banklab/financeContents/dto/FinanceTermsDto.java
  src/main/java/com/banklab/financeContents/dto/FinanceTermsResponse.java
  src/main/java/com/banklab/financeContents/dto/NewsItemDto.java
  src/main/java/com/banklab/financeContents/dto/RealtimeDataDto.java
  src/main/java/com/banklab/financeContents/dto/StockSearchResultDto.java
  src/main/java/com/banklab/financeContents/dto/UpbitCandleDto.java
  src/main/java/com/banklab/financeContents/dto/UpbitDataResponseDto.java
  src/main/java/com/banklab/financeContents/dto/UpbitMarketDto.java
  src/main/java/com/banklab/financeContents/dto/UpbitTickerDto.java
  src/main/java/com/banklab/financeContents/mapper/FinanceStockMapper.java
  src/main/java/com/banklab/financeContents/mapper/FinanceTermMapper.java
  src/main/java/com/banklab/financeContents/mapper/UpbitMapper.java
  src/main/java/com/banklab/financeContents/mapper/UserQuizResultMapper.java
  src/main/java/com/banklab/financeContents/scheduler/FinanceStockScheduler.java
  src/main/java/com/banklab/financeContents/scheduler/UpbitDataScheduler.java
  src/main/java/com/banklab/financeContents/service/FinanceQuizService.java
  src/main/java/com/banklab/financeContents/service/FinanceQuizServiceImpl.java
  src/main/java/com/banklab/financeContents/service/FinanceStockService.java
  src/main/java/com/banklab/financeContents/service/FinanceStockServiceImpl.java
  src/main/java/com/banklab/financeContents/service/FinanceTermCsvService.java
  src/main/java/com/banklab/financeContents/service/FinanceTermCsvServiceImpl.java
  src/main/java/com/banklab/financeContents/service/FinanceTermsService.java
  src/main/java/com/banklab/financeContents/service/NaverNewsService.java
  src/main/java/com/banklab/financeContents/service/PublicDataStockService.java
  src/main/java/com/banklab/financeContents/service/UpbitApiService.java
  src/main/java/com/banklab/financeContents/service/UpbitDataService.java
  src/main/java/com/banklab/financeContents/util/UpbitDataCollectorRunner.java
  src/main/java/com/banklab/security/policy/AccessPolicy.java
  src/main/resources/application.properties
  src/main/resources/com/banklab/financeContents/UpbitMapper.xml
  src/main/resources/com/banklab/financeContents/mapper/FinanceStockMapper.xml
  src/main/resources/com/banklab/financeContents/mapper/FinanceTermMapper.xml
  src/main/resources/com/banklab/financeContents/mapper/UpbitMapper.xml
  src/main/resources/com/banklab/financeContents/mapper/UserQuizResultMapper.xml
  src/main/resources/com/banklab/mapper/UpbitMapper.xml
Labels: 🐛 bugfix, ✨ feature

#36 [BNK-222] 상품 버그 수정
  src/main/java/com/banklab/product/controller/RentHouseLoanDetailController.java
  src/main/java/com/banklab/product/dto/ProductRateInfo.java
  src/main/java/com/banklab/product/dto/annuity/AnnuityWithOptionsDto.java
  src/main/java/com/banklab/product/service/ProductRateServiceImpl.java
  src/main/java/com/banklab/product/service/annuity/AnnuityDetailServiceImpl.java
  src/main/java/com/banklab/typetest/dto/TypeTestResultDTO.java
  src/main/java/com/banklab/typetest/service/ProductRecommendationServiceImpl.java
  src/main/java/com/banklab/typetest/service/TypeTestServiceImpl.java
Labels: 🐛 bugfix, ✨ feature

#37 [BNK-168] 주식,가상화페 [거래량,거래대금,등락률] 상위 N개 조회 엔드포인트 추가
  .gitignore
  src/main/java/com/banklab/financeContents/controller/StockController.java
  src/main/java/com/banklab/financeContents/controller/UpbitController.java
  src/main/java/com/banklab/financeContents/mapper/FinanceStockMapper.java
  src/main/java/com/banklab/financeContents/service/FinanceStockService.java
  src/main/java/com/banklab/financeContents/service/FinanceStockServiceImpl.java
  src/main/resources/com/banklab/financeContents/mapper/FinanceStockMapper.xml
Labels: ✨ feature

#39 [BNK-168] Feat : 푼 문제로 레벨업하는 기능 추가 / 정답률 계산 서비스,컨트롤러 추가
  src/main/java/com/banklab/financeContents/controller/FinanceQuizController.java
  src/main/java/com/banklab/financeContents/domain/UserQuizResultVO.java
  src/main/java/com/banklab/financeContents/dto/UserQuizResultDTO.java
  src/main/java/com/banklab/financeContents/dto/UserQuizStatsDTO.java
  src/main/java/com/banklab/financeContents/mapper/UserQuizResultMapper.java
  src/main/java/com/banklab/financeContents/service/FinanceQuizService.java
  src/main/java/com/banklab/financeContents/service/FinanceQuizServiceImpl.java
  src/main/resources/com/banklab/financeContents/mapper/UserQuizResultMapper.xml
Labels: ✨ feature

#40 [BNK-248] Chore: 스웨거 API 명세서를 위한 1차 수정
  src/main/java/com/banklab/account/controller/AccountController.java
  src/main/java/com/banklab/config/ServletConfig.java
  src/main/java/com/banklab/config/SwaggerConfig.java
  src/main/java/com/banklab/financeContents/controller/ExchangeRateController.java
  src/main/java/com/banklab/financeContents/controller/GoldController.java
  src/main/java/com/banklab/financeContents/controller/NewsController.java
  src/main/java/com/banklab/financeContents/controller/StockController.java
  src/main/java/com/banklab/financeContents/controller/UpbitController.java
  src/main/java/com/banklab/financeContents/dto/NewsItemDto.java
  src/main/java/com/banklab/member/controller/MemberController.java
  src/main/java/com/banklab/peerCompare/controller/ComparisonController.java
  src/main/java/com/banklab/security/account/dto/UserInfoDTO.java
  src/main/java/com/banklab/security/controller/AuthController.java
  src/main/java/com/banklab/security/policy/AccessPolicy.java
  src/main/java/com/banklab/stock/controller/StockApiController.java
  src/main/java/com/banklab/typetest/controller/TypeTestController.java
  src/main/java/com/banklab/typetest/domain/Question.java
  src/main/java/com/banklab/typetest/dto/QuestionsResponseDTO.java
  src/main/java/com/banklab/typetest/dto/RecommendedProductDTO.java
  src/main/java/com/banklab/typetest/dto/TypeTestResultDTO.java
  src/main/java/com/banklab/verification/controller/VerificationController.java
Labels: 📄 documentation

#41 [BNK-168] 퀴즈결과 구조 변경 후 발생하는 버그 수정
  src/main/java/com/banklab/financeContents/controller/FinanceQuizController.java
  src/main/java/com/banklab/financeContents/dto/UserQuizResultDTO.java
  src/main/resources/application.properties
  src/main/resources/com/banklab/financeContents/mapper/UserQuizResultMapper.xml
Labels: 🐛 bugfix

#43 Chore : PR 템플릿 수정
  pull_request_template.md
Labels: 📄 documentation

#42 [BNK-194] 캐릭터 기능 구현
  src/main/java/com/banklab/activity/controller/ActivityLogController.java
  src/main/java/com/banklab/activity/domain/CompareUsageLogVO.java
  src/main/java/com/banklab/activity/domain/ContentType.java
  src/main/java/com/banklab/activity/domain/ContentViewLogVO.java
  src/main/java/com/banklab/activity/domain/MyDataLogVO.java
  src/main/java/com/banklab/activity/domain/SpendingReportViewLogVO.java
  src/main/java/com/banklab/activity/dto/ContentViewLogDTO.java
  src/main/java/com/banklab/activity/dto/MyDataFetchLogDTO.java
  src/main/java/com/banklab/activity/dto/ReportViewLogDTO.java
  src/main/java/com/banklab/activity/mapper/CompareUsageLogMapper.java
  src/main/java/com/banklab/activity/mapper/ContentViewLogMapper.java
  src/main/java/com/banklab/activity/mapper/MyDataLogMapper.java
  src/main/java/com/banklab/activity/mapper/SpendingReportViewLogMapper.java
  src/main/java/com/banklab/activity/service/ActivityService.java
  src/main/java/com/banklab/activity/service/ActivityServiceImpl.java
  src/main/java/com/banklab/character/controller/CharacterController.java
  src/main/java/com/banklab/character/domain/CharacterLevelVO.java
  src/main/java/com/banklab/character/domain/CharacterVO.java
  src/main/java/com/banklab/character/domain/MemberCharacterVO.java
  src/main/java/com/banklab/character/dto/CharacterDTO.java
  src/main/java/com/banklab/character/mapper/CharacterMapper.java
  src/main/java/com/banklab/character/service/CharacterService.java
  src/main/java/com/banklab/character/service/CharacterServiceImpl.java
  src/main/java/com/banklab/config/RootConfig.java
  src/main/java/com/banklab/config/ServletConfig.java
  src/main/java/com/banklab/mission/controller/MissionController.java
  src/main/java/com/banklab/mission/domain/ConditionKey.java
  src/main/java/com/banklab/mission/domain/ConditionType.java
  src/main/java/com/banklab/mission/domain/MissionCycle.java
  src/main/java/com/banklab/mission/domain/MissionProgressVO.java
  src/main/java/com/banklab/mission/domain/MissionType.java
  src/main/java/com/banklab/mission/domain/MissionVO.java
  src/main/java/com/banklab/mission/dto/MissionDTO.java
  src/main/java/com/banklab/mission/dto/MissionProgressDTO.java
  src/main/java/com/banklab/mission/dto/MissionStateDTO.java
  src/main/java/com/banklab/mission/dto/MissionsResponseDTO.java
  src/main/java/com/banklab/mission/evaluator/BooleanMissionEvaluator.java
  src/main/java/com/banklab/mission/evaluator/CountMissionEvaluator.java
  src/main/java/com/banklab/mission/evaluator/CriteriaMissionEvaluator.java
  src/main/java/com/banklab/mission/evaluator/EvaluatorRegistry.java
  src/main/java/com/banklab/mission/evaluator/MissionEvaluator.java
  src/main/java/com/banklab/mission/evaluator/RatioMissionEvaluator.java
  src/main/java/com/banklab/mission/event/MissionCompletedEvent.java
  src/main/java/com/banklab/mission/event/listener/CharacterEventListener.java
  src/main/java/com/banklab/mission/mapper/MissionMapper.java
  src/main/java/com/banklab/mission/mapper/MissionProgressMapper.java
  src/main/java/com/banklab/mission/service/MissionService.java
  src/main/java/com/banklab/mission/service/MissionServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/com/banklab/activity/mapper/CompareUsageLogMapper.xml
  src/main/resources/com/banklab/activity/mapper/ContentViewLogMapper.xml
  src/main/resources/com/banklab/activity/mapper/MyDataLogMapper.xml
  src/main/resources/com/banklab/activity/mapper/SpendingReportViewLogMapper.xml
  src/main/resources/com/banklab/character/mapper/CharacterMapper.xml
  src/main/resources/com/banklab/mission/mapper/MissionMapper.xml
  src/main/resources/com/banklab/mission/mapper/MissionProgressMapper.xml
  src/main/resources/mybatis-config.xml
Labels: ✨ feature

#46 [BNK-168] 주식 "시가" 데이터 추가
  src/main/java/com/banklab/financeContents/controller/StockController.java
  src/main/java/com/banklab/financeContents/mapper/FinanceStockMapper.java
  src/main/java/com/banklab/financeContents/service/FinanceStockService.java
  src/main/java/com/banklab/financeContents/service/FinanceStockServiceImpl.java
  src/main/resources/com/banklab/financeContents/mapper/FinanceStockMapper.xml
Labels: ✨ feature

#49 [BNK-258] Feat: 소비 분석 고도화
  src/main/java/com/banklab/category/kakaomap/service/KakaoMapService.java
  src/main/java/com/banklab/category/service/CategoryService.java
  src/main/java/com/banklab/common/redis/RedisService.java
  src/main/java/com/banklab/transaction/controller/TransactionApiController.java
  src/main/java/com/banklab/transaction/mapper/TransactionMapper.java
  src/main/java/com/banklab/transaction/service/AsyncTransactionServiceImpl.java
  src/main/java/com/banklab/transaction/service/TransactionService.java
  src/main/java/com/banklab/transaction/service/TransactionServiceImpl.java
  src/main/java/com/banklab/transaction/summary/mapper/SummaryMapper.java
  src/main/java/com/banklab/transaction/summary/service/SummaryBatchService.java
  src/main/java/com/banklab/transaction/summary/service/SummaryBatchServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/com/banklab/transaction/mapper/TransactionMapper.xml
  src/main/resources/com/banklab/transaction/summary/mapper/SummaryMapper.xml
Labels: 🐛 bugfix, ✨ feature

#50 [BNK-168] 주식 컨트롤러 코드 오류 수정
  src/main/java/com/banklab/financeContents/controller/StockController.java
  src/main/java/com/banklab/financeContents/service/FinanceStockServiceImpl.java
  src/main/java/com/banklab/financeContents/service/PublicDataStockService.java
Labels: 🐛 bugfix

#51 [BNK-265] Fix : 주식 데이터 불러오기 에러 해결
  src/main/java/com/banklab/financeContents/service/FinanceStockServiceImpl.java
  src/main/java/com/banklab/financeContents/service/PublicDataStockService.java
  src/main/resources/application.properties
Labels: 🐛 bugfix

#52 [BNK-251] 캐릭터 미션 구조 변경
  src/main/java/com/banklab/account/service/AccountServiceImpl.java
  src/main/java/com/banklab/activity/controller/ActivityLogController.java
  src/main/java/com/banklab/activity/domain/EventType.java
  src/main/java/com/banklab/activity/mapper/ActivityMapper.java
  src/main/java/com/banklab/activity/mapper/CompareUsageLogMapper.java
  src/main/java/com/banklab/activity/mapper/ContentViewLogMapper.java
  src/main/java/com/banklab/activity/mapper/MyDataLogMapper.java
  src/main/java/com/banklab/activity/mapper/SpendingReportViewLogMapper.java
  src/main/java/com/banklab/activity/service/ActivityService.java
  src/main/java/com/banklab/activity/service/ActivityServiceImpl.java
  src/main/java/com/banklab/activity/util/IdemKeys.java
  src/main/java/com/banklab/calculator/controller/CalculatorController.java
  src/main/java/com/banklab/character/controller/CharacterController.java
  src/main/java/com/banklab/character/mapper/CharacterMapper.java
  src/main/java/com/banklab/character/service/CharacterService.java
  src/main/java/com/banklab/character/service/CharacterServiceImpl.java
  src/main/java/com/banklab/common/util/Periods.java
  src/main/java/com/banklab/financeContents/controller/FinanceQuizController.java
  src/main/java/com/banklab/financeContents/service/FinanceQuizService.java
  src/main/java/com/banklab/financeContents/service/FinanceQuizServiceImpl.java
  src/main/java/com/banklab/mission/controller/MissionController.java
  src/main/java/com/banklab/mission/domain/ExpGrantVO.java
  src/main/java/com/banklab/mission/domain/MissionProgressVO.java
  src/main/java/com/banklab/mission/domain/MissionVO.java
  src/main/java/com/banklab/mission/dto/MissionProgressDTO.java
  src/main/java/com/banklab/mission/evaluator/BooleanMissionEvaluator.java
  src/main/java/com/banklab/mission/evaluator/CountMissionEvaluator.java
  src/main/java/com/banklab/mission/event/AssetSyncedEvent.java
  src/main/java/com/banklab/mission/event/MissionCompletedEvent.java
  src/main/java/com/banklab/mission/event/MissionTriggerEvent.java
  src/main/java/com/banklab/mission/event/listener/AssetMissionListener.java
  src/main/java/com/banklab/mission/event/listener/CharacterEventListener.java
  src/main/java/com/banklab/mission/event/listener/MissionEventListener.java
  src/main/java/com/banklab/mission/mapper/MissionMapper.java
  src/main/java/com/banklab/mission/mapper/MissionProgressMapper.java
  src/main/java/com/banklab/mission/service/MissionProgressService.java
  src/main/java/com/banklab/mission/service/MissionProgressServiceImpl.java
  src/main/java/com/banklab/mission/service/MissionService.java
  src/main/java/com/banklab/mission/service/MissionServiceImpl.java
  src/main/java/com/banklab/typetest/controller/TypeTestController.java
  src/main/resources/com/banklab/activity/mapper/ActivityMapper.xml
  src/main/resources/com/banklab/activity/mapper/CompareUsageLogMapper.xml
  src/main/resources/com/banklab/activity/mapper/ContentViewLogMapper.xml
  src/main/resources/com/banklab/activity/mapper/MyDataLogMapper.xml
  src/main/resources/com/banklab/activity/mapper/SpendingReportViewLogMapper.xml
  src/main/resources/com/banklab/character/mapper/CharacterMapper.xml
  src/main/resources/com/banklab/mission/mapper/MissionMapper.xml
  src/main/resources/com/banklab/mission/mapper/MissionProgressMapper.xml
  src/test/java/com/banklab/member/service/MemberServiceImplTest.java
Labels: 🐛 bugfix, ✨ feature

#54 [BNK-288] Fix : UI 수정 중 오류메시지 전달 상세하게 수정
  README.md
  src/main/java/com/banklab/account/controller/AccountController.java
  src/main/java/com/banklab/account/service/AccountResponse.java
  src/main/java/com/banklab/cash/controller/CashController.java
  src/main/java/com/banklab/codef/service/RequestConnectedId.java
  src/main/java/com/banklab/stock/controller/StockApiController.java
  src/main/java/com/banklab/stock/service/StockResponse.java
Labels: 🐛 bugfix

#55 Refactoring: kakao & perplexity 제거
  src/main/java/com/banklab/category/kakaomap/client/KakaoMapClient.java
  src/main/java/com/banklab/category/kakaomap/dto/KakaoMapSearchResponseDto.java
  src/main/java/com/banklab/category/mapper/CategoryMapper.java
  src/main/java/com/banklab/category/perplexity/controller/PerplexityApiController.java
  src/main/java/com/banklab/category/perplexity/dto/PerplexityRequestDto.java
  src/main/java/com/banklab/category/perplexity/dto/PerplexityResponseDto.java
  src/main/java/com/banklab/category/perplexity/service/PerplexityService.java
  src/main/java/com/banklab/category/service/CategoryService.java
  src/main/java/com/banklab/category/service/UtilService.java
  src/main/java/com/banklab/config/RootConfig.java
  src/main/java/com/banklab/transaction/service/AsyncTransactionServiceImpl.java
  src/main/resources/application.properties
Labels: 🔁 refactor

#58 [Comment-Transaction] 거래 내역 분석 관련 테스트 코드 및 주석 작성
  build.gradle
  src/main/java/com/banklab/account/controller/AccountController.java
  src/main/java/com/banklab/category/gemini/service/GeminiService.java
  src/main/java/com/banklab/category/service/CategoryService.java
  src/main/java/com/banklab/peerCompare/service/ComparisonService.java
  src/main/java/com/banklab/peerCompare/service/ComparisonServiceImpl.java
  src/main/java/com/banklab/transaction/service/AsyncTransactionService.java
  src/main/java/com/banklab/transaction/service/AsyncTransactionServiceImpl.java
  src/main/java/com/banklab/transaction/service/TransactionResponse.java
  src/main/java/com/banklab/transaction/service/TransactionService.java
  src/main/java/com/banklab/transaction/service/TransactionServiceImpl.java
  src/main/java/com/banklab/transaction/summary/batch/tasklet/UpsertTransactionTesklet.java
  src/main/java/com/banklab/transaction/summary/service/SummaryBatchService.java
  src/main/java/com/banklab/transaction/summary/service/SummaryBatchServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/banklab/category/gemini/service/GeminiServiceTest.java
  src/test/java/com/banklab/category/service/CategoryServiceTest.java
  src/test/java/com/banklab/category/service/UtilServiceTest.java
  src/test/java/com/banklab/transaction/service/AsyncTransactionServiceImplConcurrencyTest.java
  src/test/java/com/banklab/transaction/service/AsyncTransactionServiceImplTest.java
  src/test/java/com/banklab/typetest/controller/TypeTestControllerTest.java
Labels: 🔁 refactor, 🧪 test

#62 [BNK-168] SQL문 서버로그 주석처리
  src/main/java/com/banklab/financeContents/controller/ExchangeRateController.java
  src/main/java/com/banklab/financeContents/controller/FinanceQuizController.java
  src/main/java/com/banklab/financeContents/controller/FinanceTermsController.java
  src/main/java/com/banklab/financeContents/controller/GoldController.java
  src/main/java/com/banklab/financeContents/controller/HealthController.java
  src/main/java/com/banklab/financeContents/controller/NewsController.java
  src/main/java/com/banklab/financeContents/controller/StockController.java
  src/main/java/com/banklab/financeContents/controller/UpbitController.java
  src/main/java/com/banklab/financeContents/scheduler/FinanceStockScheduler.java
  src/main/java/com/banklab/financeContents/scheduler/UpbitDataScheduler.java
  src/main/java/com/banklab/financeContents/service/ExchangeRateService.java
  src/main/java/com/banklab/financeContents/service/FinanceQuizServiceImpl.java
  src/main/java/com/banklab/financeContents/service/FinanceStockServiceImpl.java
  src/main/java/com/banklab/financeContents/service/FinanceTermCsvServiceImpl.java
  src/main/java/com/banklab/financeContents/service/GoldPriceService.java
  src/main/java/com/banklab/financeContents/service/PublicDataStockService.java
  src/main/java/com/banklab/financeContents/service/UpbitApiService.java
  src/main/java/com/banklab/financeContents/service/UpbitDataService.java
  src/main/java/com/banklab/financeContents/util/ExchangeRateUtil.java
  src/main/java/com/banklab/financeContents/util/StockDataUpdateRunner.java
  src/main/java/com/banklab/financeContents/util/UpbitDataCollectorRunner.java
  src/main/resources/application.properties
  src/main/resources/log4j2.xml
Labels: 📄 documentation
